#!/usr/bin/env playonlinux-bash
#
# This file is part of playonlinux-docker
# https://github.com/mgafner/playonlinux-docker
#
# This is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file.  If not, see <http://www.gnu.org/licenses/>.

[ "$PLAYONLINUX" = "" ] && exit 0
source "$PLAYONLINUX/lib/sources"
 
POL_SetupWindow_Init

PREFIX="wine.2.12"

if [ "$(POL_Wine_PrefixExists "$PREFIX")" = "False" ]
then
  # The préfixe doesn't exist
  POL_Wine_SelectPrefix "wine.2.12"
  POL_Wine_PrefixCreate "2.12-staging"
  POL_Wine_InstallFonts
else
  POL_Wine_SelectPrefix "wine.2.12"
  POL_Shortcut "gta-vc.exe" "GTA Vice City"
  POL_Shortcut "VCMPBrowser.exe" "GTA Vice City Multiplayer"
fi

POL_SetupWindow_Close
exit
